#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Pi-hole
# Runs the PHP-FPM daemon
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

if hass.config.true 'use_unbound_resolver'; then
    unbound_port=$(hass.config.get 'unbound_port')
    hass.log.debug "Starting Unbound DNS resolver on port ${unbound_port}"
    exec unbound -v -d
fi